extends Node3D
var player_models:Array[Node]=[]

@onready var player_master:Node=$"../../../.."
@onready var weapon_mag_3rd:Node=$gun_body/magazine
@onready var shoot_point_node:Node=$shoot_point
func _ready() -> void:
	player_models.append($gun_body)
	player_models.append($gun_body/magazine)
	player_models.append($gun_body/sight)
	player_models.append($gun_body/barrel)
	player_models.append($gun_body/gun_body2)
	player_models.append($gun_body/trigger)
	player_models.append($gun_body/bullet_set)
	if player_master.view_mode_player==0:
		for pm in range(player_models.size()):
			player_models[pm].set_cast_shadows_setting(3)
	if player_master.view_mode_player==1:
		for pm in range(player_models.size()):
			player_models[pm].set_cast_shadows_setting(1)
func die_cast_shadows():
	for pm in range(player_models.size()):
			player_models[pm].set_cast_shadows_setting(1)

var ready_to_scene:bool=false

func _physics_process(delta: float) -> void:
	if ready_to_scene==false:
		if UserData.texture_size_data==256:
			var gun_body_0_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_0.tres")
			var gun_body_1_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_1.tres")
			var gun_body_2_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_2.tres")
			var gun_body_3_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_3.tres")
			var gun_body_4_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_4.tres")
			var gun_body_5_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_5.tres")
			var gun_body_6_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_6.tres")
			var gun_body_7_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_7.tres")
			var gun_body_8_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_8.tres")
			var gun_body_9_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_9.tres")
			var gun_body_10_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body_10.tres")
			var magazine_material:Resource=preload("res://assets/materials_prefab/sniper/256/magazine.tres")
			var sight_0_material:Resource=preload("res://assets/materials_prefab/sniper/256/sight_0.tres")
			var sight_1_material:Resource=preload("res://assets/materials_prefab/sniper/256/sight_1.tres")
			var sight_2_material:Resource=preload("res://assets/materials_prefab/sniper/256/sight_2.tres")
			var sight_3_material:Resource=preload("res://assets/materials_prefab/sniper/256/sight_3.tres")
			var sight_4_material:Resource=preload("res://assets/materials_prefab/sniper/256/sight_4.tres")
			var sight_5_material:Resource=preload("res://assets/materials_prefab/sniper/256/sight_5.tres")
			var sight_6_material:Resource=preload("res://assets/materials_prefab/sniper/256/sight_6.tres")
			var sight_7_material:Resource=preload("res://assets/materials_prefab/sniper/256/sight_7.tres")
			var barrel_material:Resource=preload("res://assets/materials_prefab/sniper/256/barrel.tres")
			var gun_body2_0_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body2_0.tres")
			var gun_body2_1_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body2_1.tres")
			var gun_body2_2_material:Resource=preload("res://assets/materials_prefab/sniper/256/gun_body2_2.tres")
			var trigger_material:Resource=preload("res://assets/materials_prefab/sniper/256/trigger.tres")
			var bullet_set_0:Resource=preload("res://assets/materials_prefab/sniper/256/bullet_set_0.tres")
			var bullet_set_1:Resource=preload("res://assets/materials_prefab/sniper/256/bullet_set_1.tres")
			var bullet_set_2:Resource=preload("res://assets/materials_prefab/sniper/256/bullet_set_2.tres")
			
			$gun_body.set_surface_override_material(0,gun_body_0_material)
			$gun_body.set_surface_override_material(1,gun_body_1_material)
			$gun_body.set_surface_override_material(2,gun_body_2_material)
			$gun_body.set_surface_override_material(3,gun_body_3_material)
			$gun_body.set_surface_override_material(4,gun_body_4_material)
			$gun_body.set_surface_override_material(5,gun_body_5_material)
			$gun_body.set_surface_override_material(6,gun_body_6_material)
			$gun_body.set_surface_override_material(7,gun_body_7_material)
			$gun_body.set_surface_override_material(8,gun_body_8_material)
			$gun_body.set_surface_override_material(9,gun_body_9_material)
			$gun_body.set_surface_override_material(10,gun_body_10_material)
			$gun_body/magazine.set_surface_override_material(0,magazine_material)
			$gun_body/sight.set_surface_override_material(0,sight_0_material)
			$gun_body/sight.set_surface_override_material(1,sight_1_material)
			$gun_body/sight.set_surface_override_material(2,sight_2_material)
			$gun_body/sight.set_surface_override_material(3,sight_3_material)
			$gun_body/sight.set_surface_override_material(4,sight_4_material)
			$gun_body/sight.set_surface_override_material(5,sight_5_material)
			$gun_body/sight.set_surface_override_material(6,sight_6_material)
			$gun_body/sight.set_surface_override_material(7,sight_7_material)
			$gun_body/barrel.set_surface_override_material(0,barrel_material)
			$gun_body/gun_body2.set_surface_override_material(0,gun_body2_0_material)
			$gun_body/gun_body2.set_surface_override_material(1,gun_body2_1_material)
			$gun_body/gun_body2.set_surface_override_material(2,gun_body2_2_material)
			$gun_body/trigger.set_surface_override_material(0,trigger_material)
			$gun_body/bullet_set.set_surface_override_material(0,bullet_set_0)
			$gun_body/bullet_set.set_surface_override_material(1,bullet_set_1)
			$gun_body/bullet_set.set_surface_override_material(2,bullet_set_2)
	
	
		if UserData.texture_size_data==512:
			var gun_body_0_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_0.tres")
			var gun_body_1_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_1.tres")
			var gun_body_2_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_2.tres")
			var gun_body_3_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_3.tres")
			var gun_body_4_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_4.tres")
			var gun_body_5_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_5.tres")
			var gun_body_6_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_6.tres")
			var gun_body_7_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_7.tres")
			var gun_body_8_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_8.tres")
			var gun_body_9_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_9.tres")
			var gun_body_10_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body_10.tres")
			var magazine_material:Resource=preload("res://assets/materials_prefab/sniper/512/magazine.tres")
			var sight_0_material:Resource=preload("res://assets/materials_prefab/sniper/512/sight_0.tres")
			var sight_1_material:Resource=preload("res://assets/materials_prefab/sniper/512/sight_1.tres")
			var sight_2_material:Resource=preload("res://assets/materials_prefab/sniper/512/sight_2.tres")
			var sight_3_material:Resource=preload("res://assets/materials_prefab/sniper/512/sight_3.tres")
			var sight_4_material:Resource=preload("res://assets/materials_prefab/sniper/512/sight_4.tres")
			var sight_5_material:Resource=preload("res://assets/materials_prefab/sniper/512/sight_5.tres")
			var sight_6_material:Resource=preload("res://assets/materials_prefab/sniper/512/sight_6.tres")
			var sight_7_material:Resource=preload("res://assets/materials_prefab/sniper/512/sight_7.tres")
			var barrel_material:Resource=preload("res://assets/materials_prefab/sniper/512/barrel.tres")
			var gun_body2_0_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body2_0.tres")
			var gun_body2_1_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body2_1.tres")
			var gun_body2_2_material:Resource=preload("res://assets/materials_prefab/sniper/512/gun_body2_2.tres")
			var trigger_material:Resource=preload("res://assets/materials_prefab/sniper/512/trigger.tres")
			var bullet_set_0:Resource=preload("res://assets/materials_prefab/sniper/512/bullet_set_0.tres")
			var bullet_set_1:Resource=preload("res://assets/materials_prefab/sniper/512/bullet_set_1.tres")
			var bullet_set_2:Resource=preload("res://assets/materials_prefab/sniper/512/bullet_set_2.tres")
			
			$gun_body.set_surface_override_material(0,gun_body_0_material)
			$gun_body.set_surface_override_material(1,gun_body_1_material)
			$gun_body.set_surface_override_material(2,gun_body_2_material)
			$gun_body.set_surface_override_material(3,gun_body_3_material)
			$gun_body.set_surface_override_material(4,gun_body_4_material)
			$gun_body.set_surface_override_material(5,gun_body_5_material)
			$gun_body.set_surface_override_material(6,gun_body_6_material)
			$gun_body.set_surface_override_material(7,gun_body_7_material)
			$gun_body.set_surface_override_material(8,gun_body_8_material)
			$gun_body.set_surface_override_material(9,gun_body_9_material)
			$gun_body.set_surface_override_material(10,gun_body_10_material)
			$gun_body/magazine.set_surface_override_material(0,magazine_material)
			$gun_body/sight.set_surface_override_material(0,sight_0_material)
			$gun_body/sight.set_surface_override_material(1,sight_1_material)
			$gun_body/sight.set_surface_override_material(2,sight_2_material)
			$gun_body/sight.set_surface_override_material(3,sight_3_material)
			$gun_body/sight.set_surface_override_material(4,sight_4_material)
			$gun_body/sight.set_surface_override_material(5,sight_5_material)
			$gun_body/sight.set_surface_override_material(6,sight_6_material)
			$gun_body/sight.set_surface_override_material(7,sight_7_material)
			$gun_body/barrel.set_surface_override_material(0,barrel_material)
			$gun_body/gun_body2.set_surface_override_material(0,gun_body2_0_material)
			$gun_body/gun_body2.set_surface_override_material(1,gun_body2_1_material)
			$gun_body/gun_body2.set_surface_override_material(2,gun_body2_2_material)
			$gun_body/trigger.set_surface_override_material(0,trigger_material)
			$gun_body/bullet_set.set_surface_override_material(0,bullet_set_0)
			$gun_body/bullet_set.set_surface_override_material(1,bullet_set_1)
			$gun_body/bullet_set.set_surface_override_material(2,bullet_set_2)
	
		if UserData.texture_size_data==1024:
			var gun_body_0_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_0.tres")
			var gun_body_1_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_1.tres")
			var gun_body_2_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_2.tres")
			var gun_body_3_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_3.tres")
			var gun_body_4_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_4.tres")
			var gun_body_5_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_5.tres")
			var gun_body_6_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_6.tres")
			var gun_body_7_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_7.tres")
			var gun_body_8_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_8.tres")
			var gun_body_9_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_9.tres")
			var gun_body_10_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body_10.tres")
			var magazine_material:Resource=preload("res://assets/materials_prefab/sniper/1024/magazine.tres")
			var sight_0_material:Resource=preload("res://assets/materials_prefab/sniper/1024/sight_0.tres")
			var sight_1_material:Resource=preload("res://assets/materials_prefab/sniper/1024/sight_1.tres")
			var sight_2_material:Resource=preload("res://assets/materials_prefab/sniper/1024/sight_2.tres")
			var sight_3_material:Resource=preload("res://assets/materials_prefab/sniper/1024/sight_3.tres")
			var sight_4_material:Resource=preload("res://assets/materials_prefab/sniper/1024/sight_4.tres")
			var sight_5_material:Resource=preload("res://assets/materials_prefab/sniper/1024/sight_5.tres")
			var sight_6_material:Resource=preload("res://assets/materials_prefab/sniper/1024/sight_6.tres")
			var sight_7_material:Resource=preload("res://assets/materials_prefab/sniper/1024/sight_7.tres")
			var barrel_material:Resource=preload("res://assets/materials_prefab/sniper/1024/barrel.tres")
			var gun_body2_0_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body2_0.tres")
			var gun_body2_1_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body2_1.tres")
			var gun_body2_2_material:Resource=preload("res://assets/materials_prefab/sniper/1024/gun_body2_2.tres")
			var trigger_material:Resource=preload("res://assets/materials_prefab/sniper/1024/trigger.tres")
			var bullet_set_0:Resource=preload("res://assets/materials_prefab/sniper/1024/bullet_set_0.tres")
			var bullet_set_1:Resource=preload("res://assets/materials_prefab/sniper/1024/bullet_set_1.tres")
			var bullet_set_2:Resource=preload("res://assets/materials_prefab/sniper/1024/bullet_set_2.tres")
			
			$gun_body.set_surface_override_material(0,gun_body_0_material)
			$gun_body.set_surface_override_material(1,gun_body_1_material)
			$gun_body.set_surface_override_material(2,gun_body_2_material)
			$gun_body.set_surface_override_material(3,gun_body_3_material)
			$gun_body.set_surface_override_material(4,gun_body_4_material)
			$gun_body.set_surface_override_material(5,gun_body_5_material)
			$gun_body.set_surface_override_material(6,gun_body_6_material)
			$gun_body.set_surface_override_material(7,gun_body_7_material)
			$gun_body.set_surface_override_material(8,gun_body_8_material)
			$gun_body.set_surface_override_material(9,gun_body_9_material)
			$gun_body.set_surface_override_material(10,gun_body_10_material)
			$gun_body/magazine.set_surface_override_material(0,magazine_material)
			$gun_body/sight.set_surface_override_material(0,sight_0_material)
			$gun_body/sight.set_surface_override_material(1,sight_1_material)
			$gun_body/sight.set_surface_override_material(2,sight_2_material)
			$gun_body/sight.set_surface_override_material(3,sight_3_material)
			$gun_body/sight.set_surface_override_material(4,sight_4_material)
			$gun_body/sight.set_surface_override_material(5,sight_5_material)
			$gun_body/sight.set_surface_override_material(6,sight_6_material)
			$gun_body/sight.set_surface_override_material(7,sight_7_material)
			$gun_body/barrel.set_surface_override_material(0,barrel_material)
			$gun_body/gun_body2.set_surface_override_material(0,gun_body2_0_material)
			$gun_body/gun_body2.set_surface_override_material(1,gun_body2_1_material)
			$gun_body/gun_body2.set_surface_override_material(2,gun_body2_2_material)
			$gun_body/trigger.set_surface_override_material(0,trigger_material)
			$gun_body/bullet_set.set_surface_override_material(0,bullet_set_0)
			$gun_body/bullet_set.set_surface_override_material(1,bullet_set_1)
			$gun_body/bullet_set.set_surface_override_material(2,bullet_set_2)
			
		ready_to_scene=true
