extends StaticBody3D


var ready_to_scene:bool=false
func _physics_process(delta: float) -> void:
	if ready_to_scene==false:
		if UserData.texture_size_data==256:
			var color1_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/256/color1.tres")
			var color2_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/256/color2.tres")
			var color3_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/256/color3.tres")
			var material_:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/256/material.tres")
			$Cube.set_surface_override_material(0,color1_material)
			$Cube.set_surface_override_material(1,color2_material)
			$Cube_001.set_surface_override_material(0,color1_material)
			$Cube_001.set_surface_override_material(1,color2_material)
			$Cube_002.set_surface_override_material(0,color1_material)
			$Cube_002.set_surface_override_material(1,color2_material)
			$Cube_003.set_surface_override_material(0,color1_material)
			$Cube_004.set_surface_override_material(0,color1_material)
			$Cube_005.set_surface_override_material(0,color2_material)
			$Cube_005.set_surface_override_material(1,color1_material)
			$Cube_006.set_surface_override_material(0,material_)
			$Cube_007.set_surface_override_material(0,material_)
			$Cube_008.set_surface_override_material(0,color3_material)
			$Cube_009.set_surface_override_material(0,color2_material)
			$Cube_010.set_surface_override_material(0,material_)
			$Cube_011.set_surface_override_material(0,color2_material)
			$Cube_012.set_surface_override_material(0,material_)
			$Cube_013.set_surface_override_material(0,material_)
			$Cube_014.set_surface_override_material(0,material_)
			$"柱体".set_surface_override_material(0,color3_material)
			$"柱体_001".set_surface_override_material(0,color3_material)
			$"立方体".set_surface_override_material(0,color3_material)
			$"立方体_001".set_surface_override_material(0,color3_material)
			$"立方体_001".set_surface_override_material(1,color2_material)
		if UserData.texture_size_data==512:
			var color1_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/512/color1.tres")
			var color2_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/512/color2.tres")
			var color3_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/512/color3.tres")
			var material_:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/512/material.tres")
			$Cube.set_surface_override_material(0,color1_material)
			$Cube.set_surface_override_material(1,color2_material)
			$Cube_001.set_surface_override_material(0,color1_material)
			$Cube_001.set_surface_override_material(1,color2_material)
			$Cube_002.set_surface_override_material(0,color1_material)
			$Cube_002.set_surface_override_material(1,color2_material)
			$Cube_003.set_surface_override_material(0,color1_material)
			$Cube_004.set_surface_override_material(0,color1_material)
			$Cube_005.set_surface_override_material(0,color2_material)
			$Cube_005.set_surface_override_material(1,color1_material)
			$Cube_006.set_surface_override_material(0,material_)
			$Cube_007.set_surface_override_material(0,material_)
			$Cube_008.set_surface_override_material(0,color3_material)
			$Cube_009.set_surface_override_material(0,color2_material)
			$Cube_010.set_surface_override_material(0,material_)
			$Cube_011.set_surface_override_material(0,color2_material)
			$Cube_012.set_surface_override_material(0,material_)
			$Cube_013.set_surface_override_material(0,material_)
			$Cube_014.set_surface_override_material(0,material_)
			$"柱体".set_surface_override_material(0,color3_material)
			$"柱体_001".set_surface_override_material(0,color3_material)
			$"立方体".set_surface_override_material(0,color3_material)
			$"立方体_001".set_surface_override_material(0,color3_material)
			$"立方体_001".set_surface_override_material(1,color2_material)
		if UserData.texture_size_data==1024:
			var color1_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/1024/color1.tres")
			var color2_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/1024/color2.tres")
			var color3_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/1024/color3.tres")
			var material_:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_scifi/1024/material.tres")
			$Cube.set_surface_override_material(0,color1_material)
			$Cube.set_surface_override_material(1,color2_material)
			$Cube_001.set_surface_override_material(0,color1_material)
			$Cube_001.set_surface_override_material(1,color2_material)
			$Cube_002.set_surface_override_material(0,color1_material)
			$Cube_002.set_surface_override_material(1,color2_material)
			$Cube_003.set_surface_override_material(0,color1_material)
			$Cube_004.set_surface_override_material(0,color1_material)
			$Cube_005.set_surface_override_material(0,color2_material)
			$Cube_005.set_surface_override_material(1,color1_material)
			$Cube_006.set_surface_override_material(0,material_)
			$Cube_007.set_surface_override_material(0,material_)
			$Cube_008.set_surface_override_material(0,color3_material)
			$Cube_009.set_surface_override_material(0,color2_material)
			$Cube_010.set_surface_override_material(0,material_)
			$Cube_011.set_surface_override_material(0,color2_material)
			$Cube_012.set_surface_override_material(0,material_)
			$Cube_013.set_surface_override_material(0,material_)
			$Cube_014.set_surface_override_material(0,material_)
			$"柱体".set_surface_override_material(0,color3_material)
			$"柱体_001".set_surface_override_material(0,color3_material)
			$"立方体".set_surface_override_material(0,color3_material)
			$"立方体_001".set_surface_override_material(0,color3_material)
			$"立方体_001".set_surface_override_material(1,color2_material)
		ready_to_scene=true
