extends Node3D

var ready_to_scene:bool=false

func _physics_process(delta: float) -> void:
	if ready_to_scene==false:
		if UserData.texture_size_data==256:
			var wall2_material:Resource=preload("res://assets/materials_prefab/maps/office/office_map/wall2/256/wall2.tres")
			$wall2_csg.material=wall2_material
			
			var celling_material:Resource=preload("res://assets/materials_prefab/maps/office/office_map/celling/256/celling.tres")
			$celling_main.set_surface_override_material(0,celling_material)
			
			var stair_material:Resource=preload("res://assets/materials_prefab/maps/office/stair/256/stair1.tres")
			var stair2_material:Resource=preload("res://assets/materials_prefab/maps/office/stair/256/stair2.tres")
			$stair_main.set_surface_override_material(0,stair_material)
			$stair_main/stair2.set_surface_override_material(0,stair2_material)
			
			$stair_main2.set_surface_override_material(0,stair_material)
			$stair_main2/stair2.set_surface_override_material(0,stair2_material)
			
			var case_material:Resource=preload("res://assets/materials_prefab/maps/office/door/256/case.tres")
			var handle_material:Resource=preload("res://assets/materials_prefab/maps/office/door/256/handle.tres")
			var lock_material:Resource=preload("res://assets/materials_prefab/maps/office/door/256/lock.tres")
			var surface_material:Resource=preload("res://assets/materials_prefab/maps/office/door/256/surface.tres")
			$door_surface11.set_surface_override_material(0,surface_material)
			$door_surface11/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface11/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door11/door_case.set_surface_override_material(0,case_material)
			
			$door_surface9.set_surface_override_material(0,surface_material)
			$door_surface9/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface9/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door9/door_case.set_surface_override_material(0,case_material)
			
			$door_surface7.set_surface_override_material(0,surface_material)
			$door_surface7/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface7/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door7/door_case.set_surface_override_material(0,case_material)
			
			$door_surface6.set_surface_override_material(0,surface_material)
			$door_surface6/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface6/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door6/door_case.set_surface_override_material(0,case_material)
			
			$door_surface5.set_surface_override_material(0,surface_material)
			$door_surface5/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface5/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door5/door_case.set_surface_override_material(0,case_material)
			
			$door4/door_surface4.set_surface_override_material(0,surface_material)
			$door4/door_surface4/door_handle1.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door4/door_surface4/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door4/door_case.set_surface_override_material(0,case_material)
			
			$door_surface3.set_surface_override_material(0,surface_material)
			$door_surface3/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface3/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door3/door_case.set_surface_override_material(0,case_material)
			
			$door_surface2.set_surface_override_material(0,surface_material)
			$door_surface2/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface2/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door2/door_case.set_surface_override_material(0,case_material)
			
			$door_surface.set_surface_override_material(0,surface_material)
			$door_surface/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door/door_case.set_surface_override_material(0,case_material)
		
		if UserData.texture_size_data==512:
			var wall2_material:Resource=preload("res://assets/materials_prefab/maps/office/office_map/wall2/512/wall2.tres")
			$wall2_csg.material=wall2_material
			
			var celling_material:Resource=preload("res://assets/materials_prefab/maps/office/office_map/celling/512/celling.tres")
			$celling_main.set_surface_override_material(0,celling_material)
			
			var stair_material:Resource=preload("res://assets/materials_prefab/maps/office/stair/512/stair1.tres")
			var stair2_material:Resource=preload("res://assets/materials_prefab/maps/office/stair/512/stair2.tres")
			$stair_main.set_surface_override_material(0,stair_material)
			$stair_main/stair2.set_surface_override_material(0,stair2_material)
			
			$stair_main2.set_surface_override_material(0,stair_material)
			$stair_main2/stair2.set_surface_override_material(0,stair2_material)
			
			var case_material:Resource=preload("res://assets/materials_prefab/maps/office/door/512/case.tres")
			var handle_material:Resource=preload("res://assets/materials_prefab/maps/office/door/512/handle.tres")
			var lock_material:Resource=preload("res://assets/materials_prefab/maps/office/door/512/lock.tres")
			var surface_material:Resource=preload("res://assets/materials_prefab/maps/office/door/512/surface.tres")
			$door_surface11.set_surface_override_material(0,surface_material)
			$door_surface11/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface11/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door11/door_case.set_surface_override_material(0,case_material)
			
			$door_surface9.set_surface_override_material(0,surface_material)
			$door_surface9/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface9/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door9/door_case.set_surface_override_material(0,case_material)
			
			$door_surface7.set_surface_override_material(0,surface_material)
			$door_surface7/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface7/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door7/door_case.set_surface_override_material(0,case_material)
			
			$door_surface6.set_surface_override_material(0,surface_material)
			$door_surface6/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface6/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door6/door_case.set_surface_override_material(0,case_material)
			
			$door_surface5.set_surface_override_material(0,surface_material)
			$door_surface5/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface5/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door5/door_case.set_surface_override_material(0,case_material)
			
			$door4/door_surface4.set_surface_override_material(0,surface_material)
			$door4/door_surface4/door_handle1.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door4/door_surface4/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door4/door_case.set_surface_override_material(0,case_material)
			
			$door_surface3.set_surface_override_material(0,surface_material)
			$door_surface3/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface3/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door3/door_case.set_surface_override_material(0,case_material)
			
			$door_surface2.set_surface_override_material(0,surface_material)
			$door_surface2/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface2/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door2/door_case.set_surface_override_material(0,case_material)
			
			$door_surface.set_surface_override_material(0,surface_material)
			$door_surface/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door/door_case.set_surface_override_material(0,case_material)
		
		if UserData.texture_size_data==1024:
			var wall2_material:Resource=preload("res://assets/materials_prefab/maps/office/office_map/wall2/1024/wall2.tres")
			$wall2_csg.material=wall2_material
			
			var celling_material:Resource=preload("res://assets/materials_prefab/maps/office/office_map/celling/1024/celling.tres")
			$celling_main.set_surface_override_material(0,celling_material)
			
			var stair_material:Resource=preload("res://assets/materials_prefab/maps/office/stair/1024/stair1.tres")
			var stair2_material:Resource=preload("res://assets/materials_prefab/maps/office/stair/1024/stair2.tres")
			$stair_main.set_surface_override_material(0,stair_material)
			$stair_main/stair2.set_surface_override_material(0,stair2_material)
			
			$stair_main2.set_surface_override_material(0,stair_material)
			$stair_main2/stair2.set_surface_override_material(0,stair2_material)
			
			var case_material:Resource=preload("res://assets/materials_prefab/maps/office/door/1024/case.tres")
			var handle_material:Resource=preload("res://assets/materials_prefab/maps/office/door/1024/handle.tres")
			var lock_material:Resource=preload("res://assets/materials_prefab/maps/office/door/1024/lock.tres")
			var surface_material:Resource=preload("res://assets/materials_prefab/maps/office/door/1024/surface.tres")
			$door_surface11.set_surface_override_material(0,surface_material)
			$door_surface11/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface11/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface11/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door11/door_case.set_surface_override_material(0,case_material)
			
			$door_surface9.set_surface_override_material(0,surface_material)
			$door_surface9/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface9/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface9/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door9/door_case.set_surface_override_material(0,case_material)
			
			$door_surface7.set_surface_override_material(0,surface_material)
			$door_surface7/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface7/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface7/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door7/door_case.set_surface_override_material(0,case_material)
			
			$door_surface6.set_surface_override_material(0,surface_material)
			$door_surface6/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface6/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface6/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door6/door_case.set_surface_override_material(0,case_material)
			
			$door_surface5.set_surface_override_material(0,surface_material)
			$door_surface5/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface5/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface5/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door5/door_case.set_surface_override_material(0,case_material)
			
			$door4/door_surface4.set_surface_override_material(0,surface_material)
			$door4/door_surface4/door_handle1.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door4/door_surface4/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door4/door_surface4/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door4/door_case.set_surface_override_material(0,case_material)
			
			$door_surface3.set_surface_override_material(0,surface_material)
			$door_surface3/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface3/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface3/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door3/door_case.set_surface_override_material(0,case_material)
			
			$door_surface2.set_surface_override_material(0,surface_material)
			$door_surface2/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface2/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface2/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door2/door_case.set_surface_override_material(0,case_material)
			
			$door_surface.set_surface_override_material(0,surface_material)
			$door_surface/door_handle1.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle2.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle3.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle4.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle5.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_handle6.set_surface_override_material(0,handle_material)
			$door_surface/door_handle1/door_lock.set_surface_override_material(0,lock_material)
			$door_surface/door_handle1/door_lock/door_lock2.set_surface_override_material(0,lock_material)
			$door/door_case.set_surface_override_material(0,case_material)
		ready_to_scene=true
