extends StaticBody3D
var ready_to_scene:bool=false

func _physics_process(delta: float) -> void:
	if ready_to_scene==false:
		if UserData.texture_size_data==256:
			var pipeline_material:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/256/pipeline.tres")
			var tv_material:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/256/tv.tres")
			var tv_screen_material:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/256/tv_screen.tres")
			var wall1_1:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/256/wall1-1.tres")
			var wall1_2:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/256/wall1-2.tres")
			var wall1_3:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/256/wall1-3.tres")
			$Cube.set_surface_override_material(0,wall1_1)
			$Cube.set_surface_override_material(1,wall1_2)
			$Cube_005.set_surface_override_material(0,wall1_3)
			$Cube_005.set_surface_override_material(1,wall1_3)
			$pipeline_001.set_surface_override_material(0,pipeline_material)
			$pipeline_002.set_surface_override_material(0,pipeline_material)
			$pipeline.set_surface_override_material(0,pipeline_material)
			$Cube_001.set_surface_override_material(0,tv_material)
			$Cube_001.set_surface_override_material(1,tv_screen_material)
			$Cube_002.set_surface_override_material(0,tv_material)
			$Cube_002.set_surface_override_material(1,tv_screen_material)
		if UserData.texture_size_data==512:
			var pipeline_material:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/512/pipeline.tres")
			var tv_material:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/512/tv.tres")
			var tv_screen_material:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/512/tv_screen.tres")
			var wall1_1:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/512/wall1-1.tres")
			var wall1_2:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/512/wall1-2.tres")
			var wall1_3:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/512/wall1-3.tres")
			$Cube.set_surface_override_material(0,wall1_1)
			$Cube.set_surface_override_material(1,wall1_2)
			$Cube_005.set_surface_override_material(0,wall1_3)
			$Cube_005.set_surface_override_material(1,wall1_3)
			$pipeline_001.set_surface_override_material(0,pipeline_material)
			$pipeline_002.set_surface_override_material(0,pipeline_material)
			$pipeline.set_surface_override_material(0,pipeline_material)
			$Cube_001.set_surface_override_material(0,tv_material)
			$Cube_001.set_surface_override_material(1,tv_screen_material)
			$Cube_002.set_surface_override_material(0,tv_material)
			$Cube_002.set_surface_override_material(1,tv_screen_material)
		if UserData.texture_size_data==1024:
			var pipeline_material:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/1024/pipeline.tres")
			var tv_material:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/1024/tv.tres")
			var tv_screen_material:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/1024/tv_screen.tres")
			var wall1_1:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/1024/wall1-1.tres")
			var wall1_2:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/1024/wall1-2.tres")
			var wall1_3:Resource=preload("res://assets/materials_prefab/maps/space_station/wall1-2/1024/wall1-3.tres")
			$Cube.set_surface_override_material(0,wall1_1)
			$Cube.set_surface_override_material(1,wall1_2)
			$Cube_005.set_surface_override_material(0,wall1_3)
			$Cube_005.set_surface_override_material(1,wall1_3)
			$pipeline_001.set_surface_override_material(0,pipeline_material)
			$pipeline_002.set_surface_override_material(0,pipeline_material)
			$pipeline.set_surface_override_material(0,pipeline_material)
			$Cube_001.set_surface_override_material(0,tv_material)
			$Cube_001.set_surface_override_material(1,tv_screen_material)
			$Cube_002.set_surface_override_material(0,tv_material)
			$Cube_002.set_surface_override_material(1,tv_screen_material)
		ready_to_scene=true
