extends StaticBody3D


var ready_to_scene:bool=false
func _physics_process(delta: float) -> void:
	if ready_to_scene==false:
		if UserData.texture_size_data==256:
			var color1_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color1.tres")
			var color2_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color2.tres")
			var color3_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color3.tres")
			var color4_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color4.tres")
			var color5_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color5.tres")
			var color6_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color6.tres")
			var color7_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color7.tres")
			var color8_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color8.tres")
			var color9_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color9.tres")
			var color10_1_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color10-1.tres")
			var color10_2_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color10-2.tres")
			var color11_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color11.tres")
			var color12_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color12.tres")
			var color13_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/256/color13.tres")
			$"立方体_001".set_surface_override_material(0,color9_material)
			$"立方体_001".set_surface_override_material(1,color10_2_material)
			$"立方体_001".set_surface_override_material(2,color11_material)
			$"立方体_001".set_surface_override_material(3,color12_material)
			$"立方体_001".set_surface_override_material(4,color13_material)
			$"立方体_001".set_surface_override_material(5,color13_material)
			$"柱体".set_surface_override_material(0,color3_material)
			$"立方体".set_surface_override_material(0,color2_material)
			$"柱体_001".set_surface_override_material(0,color4_material)
			$"柱体_002".set_surface_override_material(0,color8_material)
			$"立方体_003".set_surface_override_material(0,color6_material)
			$"立方体_005".set_surface_override_material(0,color7_material)
			$"立方体_005".set_surface_override_material(1,color10_1_material)
			$"立方体_006".set_surface_override_material(0,color7_material)
			$"立方体_006".set_surface_override_material(1,color10_1_material)
			$"立方体_008".set_surface_override_material(0,color7_material)
			$"立方体_008".set_surface_override_material(1,color10_1_material)
			$"立方体_009".set_surface_override_material(0,color7_material)
			$"立方体_009".set_surface_override_material(1,color10_1_material)
			$"立方体_011".set_surface_override_material(0,color1_material)
			$"立方体_012".set_surface_override_material(0,color1_material)
			$"立方体_015".set_surface_override_material(0,color1_material)
			$"立方体_016".set_surface_override_material(0,color1_material)
			$"柱体_003".set_surface_override_material(0,color4_material)
			$"立方体_021".set_surface_override_material(0,color6_material)
			$"立方体_022".set_surface_override_material(0,color6_material)
			$"立方体_023".set_surface_override_material(0,color6_material)
		if UserData.texture_size_data==512:
			var color1_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color1.tres")
			var color2_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color2.tres")
			var color3_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color3.tres")
			var color4_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color4.tres")
			var color5_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color5.tres")
			var color6_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color6.tres")
			var color7_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color7.tres")
			var color8_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color8.tres")
			var color9_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color9.tres")
			var color10_1_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color10-1.tres")
			var color10_2_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color10-2.tres")
			var color11_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color11.tres")
			var color12_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color12.tres")
			var color13_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/512/color13.tres")
			$"立方体_001".set_surface_override_material(0,color9_material)
			$"立方体_001".set_surface_override_material(1,color10_2_material)
			$"立方体_001".set_surface_override_material(2,color11_material)
			$"立方体_001".set_surface_override_material(3,color12_material)
			$"立方体_001".set_surface_override_material(4,color13_material)
			$"立方体_001".set_surface_override_material(5,color13_material)
			$"柱体".set_surface_override_material(0,color3_material)
			$"立方体".set_surface_override_material(0,color2_material)
			$"柱体_001".set_surface_override_material(0,color4_material)
			$"柱体_002".set_surface_override_material(0,color8_material)
			$"立方体_003".set_surface_override_material(0,color6_material)
			$"立方体_005".set_surface_override_material(0,color7_material)
			$"立方体_005".set_surface_override_material(1,color10_1_material)
			$"立方体_006".set_surface_override_material(0,color7_material)
			$"立方体_006".set_surface_override_material(1,color10_1_material)
			$"立方体_008".set_surface_override_material(0,color7_material)
			$"立方体_008".set_surface_override_material(1,color10_1_material)
			$"立方体_009".set_surface_override_material(0,color7_material)
			$"立方体_009".set_surface_override_material(1,color10_1_material)
			$"立方体_011".set_surface_override_material(0,color1_material)
			$"立方体_012".set_surface_override_material(0,color1_material)
			$"立方体_015".set_surface_override_material(0,color1_material)
			$"立方体_016".set_surface_override_material(0,color1_material)
			$"柱体_003".set_surface_override_material(0,color4_material)
			$"立方体_021".set_surface_override_material(0,color6_material)
			$"立方体_022".set_surface_override_material(0,color6_material)
			$"立方体_023".set_surface_override_material(0,color6_material)
		if UserData.texture_size_data==1024:
			var color1_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color1.tres")
			var color2_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color2.tres")
			var color3_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color3.tres")
			var color4_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color4.tres")
			var color5_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color5.tres")
			var color6_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color6.tres")
			var color7_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color7.tres")
			var color8_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color8.tres")
			var color9_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color9.tres")
			var color10_1_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color10-1.tres")
			var color10_2_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color10-2.tres")
			var color11_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color11.tres")
			var color12_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color12.tres")
			var color13_material:Resource=preload("res://assets/materials_prefab/maps/blood_strike/wall_main/1024/color13.tres")
			$"立方体_001".set_surface_override_material(0,color9_material)
			$"立方体_001".set_surface_override_material(1,color10_2_material)
			$"立方体_001".set_surface_override_material(2,color11_material)
			$"立方体_001".set_surface_override_material(3,color12_material)
			$"立方体_001".set_surface_override_material(4,color13_material)
			$"立方体_001".set_surface_override_material(5,color13_material)
			$"柱体".set_surface_override_material(0,color3_material)
			$"立方体".set_surface_override_material(0,color2_material)
			$"柱体_001".set_surface_override_material(0,color4_material)
			$"柱体_002".set_surface_override_material(0,color8_material)
			$"立方体_003".set_surface_override_material(0,color6_material)
			$"立方体_005".set_surface_override_material(0,color7_material)
			$"立方体_005".set_surface_override_material(1,color10_1_material)
			$"立方体_006".set_surface_override_material(0,color7_material)
			$"立方体_006".set_surface_override_material(1,color10_1_material)
			$"立方体_008".set_surface_override_material(0,color7_material)
			$"立方体_008".set_surface_override_material(1,color10_1_material)
			$"立方体_009".set_surface_override_material(0,color7_material)
			$"立方体_009".set_surface_override_material(1,color10_1_material)
			$"立方体_011".set_surface_override_material(0,color1_material)
			$"立方体_012".set_surface_override_material(0,color1_material)
			$"立方体_015".set_surface_override_material(0,color1_material)
			$"立方体_016".set_surface_override_material(0,color1_material)
			$"柱体_003".set_surface_override_material(0,color4_material)
			$"立方体_021".set_surface_override_material(0,color6_material)
			$"立方体_022".set_surface_override_material(0,color6_material)
			$"立方体_023".set_surface_override_material(0,color6_material)
		ready_to_scene=true
